language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t sandravlado/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sandravlado/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-013909246208"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
